### ISSUE TITLE
Code not running

### ISSUE THREAD

**Issue by iangagnon** [petebachant/CFT-vectors#6]
I ran the code from from both a bash terminal and Spyder and get the error message below:

> usage: cft_vectors.py [-h] [--angle ANGLE] [--show] [--save]
>                       {figure,diagram,animation}
> cft_vectors.py: error: too few arguments

`I'm trying to dig into this code to start making some predictions about forces on stationary (non rotating) CFT rotors in currents and waves.

**Comment by petebachant** [comment]
Ah, so this script needs some command line arguments. You can set these in Spyder using this icon:

![image](https://cloud.githubusercontent.com/assets/4604869/19630851/848b25b6-9960-11e6-8122-1e44f3f4610b.png)

The message is telling you there is one positional argument for what to generate, of which the choices are `{figure,diagram,animation}`. `figure` creates a plot of some stuff versus azimuthal angle, `diagram` makes the free body diagram, and `animation`, makes an animation, heh. 

There are also arguments for what angle to create the diagram (e.g., `--angle 60`), and if you want to save the figures, etc.

**Comment by iangagnon** [comment]
That did the trick. She's working now! Thanks Pete. Hope things are going well at the new job.

Ian
